name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Santiago
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
      - AGENCIA=1

    networks:
      - testing_net
    depends_on:
      - server

  server:
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
