networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
version: '3'
